[target.aarch64-unknown-linux-gnu]
# Install libssl-dev:arm64, see <https://github.com/cross-rs/cross/blob/main/docs/custom_images.md#adding-dependencies-to-existing-images>
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get --assume-yes install gcc:$CROSS_DEB_ARCH cmake:$CROSS_DEB_ARCH pkg-config:$CROSS_DEB_ARCH libssl-dev:$CROSS_DEB_ARCH protobuf-compiler:$CROSS_DEB_ARCH"
]